//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pacient
    {
        public int Id { get; set; }
        public string Pacient_FIO { get; set; }
        public string Polis_number { get; set; }
        public string Adres { get; set; }
        public string Birth_day { get; set; }
        public string Uchastok_number { get; set; }
    
        public virtual Uchastok Uchastok { get; set; }
    }
}
